### ISSUE TITLE
CentOS and windows Maya 2019/2020 TypeError

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/anim_picker#15]
reported in the forum http://forum.mgear-framework.com/t/animpicker-issue-with-maya-2020/1177

```
# Traceback (most recent call last):
#   File "/home/m.fransolet/maya/modules/mGear/3.4.0/scripts/mgear/anim_picker/gui.py", line 460, in add_picker_item
#     namespace=self.namespace)
#   File "/home/m.fransolet/maya/modules/mGear/3.4.0/scripts/mgear/anim_picker/widgets/picker_widgets.py", line 1721, in __init__
#     self.text = GraphicText(parent=self)
#   File "/home/m.fransolet/maya/modules/mGear/3.4.0/scripts/mgear/anim_picker/widgets/picker_widgets.py", line 1637, in __init__
#     self.set_size()
#   File "/home/m.fransolet/maya/modules/mGear/3.4.0/scripts/mgear/anim_picker/widgets/picker_widgets.py", line 1659, in set_size
#     self.center_on_parent()
#   File "/home/m.fransolet/maya/modules/mGear/3.4.0/scripts/mgear/anim_picker/widgets/picker_widgets.py", line 1689, in center_on_parent
#     self.setPos(-center_pos * self.scale_transform)
# TypeError: # 'PySide2.QtCore.QPointF.__mul__' called with wrong argument types:
#   PySide2.QtCore.QPointF.__mul__(QTransform)
# Supported signatures:
  PySide2.QtCore.QPointF.__mul__(float)

**Comment by miquelcampos** [comment]
This error is also affecting windows in Maya 2020
